#!/bin/perl
# [Gedit Tool]
# Name=F4行首复制行
# Input=line
# Output=insert
# Applicability=titled
# Save-files=nothing
# Shortcut=F4


use 5.010;

#如何发送Home
#keysym 0xff50, Home
#$HOME_KEY = pack "H4", "ff50";
#$HOME_KEY = pack "H4", "50ff";
#print $HOME_KEY;
#print chr(0xff);
#print chr(0x50)
#^[[H
#1b, 5b, 48
#print chr(0x1b);
#print chr(0x5b);
#print chr(0x48);
#print "\x1b\x5b\x48";
#print "\x50\xff";
#print "\n";
#print "\x0a";
say <STDIN>;
