#!/bin/bash

redB='\x1b[1;31m'; blueB='\x1b[1;34m'; greenB='\x1b[1;32m'; end='\x1b[0m';

if [ ! $1 ]; then
	echo "Find filename in current directory, need (multi) parameter."; exit
fi
#不搜索隐藏文件夹
cmd='find . ! -path "*/.*" '
color="|sed 'h;s:.*/::;"
for p in $*; do
cmd=$cmd"-iname \"*$p*\" "
color=$color"s/$p/$redB&$end/g;"
done
color=$color"x;s:[^/]\+$::g;G;s/\n//'"
echo -e "$blueB>>>> $cmd\n$end"
eval $cmd$color
