#!/usr/bin/perl

use 5.010;

$Bred="\e[1;31m"; $Bgreen="\e[1;32m"; $Byellow="\e[1;33m";
$Bblue="\e[1;34m"; $Bpurple="\e[1;35m"; $normal="\e[0m";
@color=($Bred,$Bgreen,$Byellow,$Bblue,$Bpurple);

while(<STDIN>){
	$c=0; chomp;
	$o=0;	# 缺省不输出，相当于grep多个关键词的"或"关系。
#    $o=1;	# 缺省输出，全文上色。
	for $arg (@ARGV){
		if($arg=~/^-/){ if(/$'/i){$o=0;last;} }	# "-"号前缀，强制排除的关键词
		if(/$arg/i){$o++;}
		s/($arg)/$color[$c%@color]$1$normal/ig;
		$c++;
	}
	say if $o;
}

