#!/bin/bash
echo "本机IP是：`routel|sed -n '2p'|awk '{print $3}'`"
ip=`routel|sed -n '2p'|awk '{print $1$2}'`
if [ $1 ]; then
	# 端口，MAC地址
	sudo /usr/bin/nmap -sS $ip
else
	# 如果对方关闭了icmp，就探测不到
	/usr/bin/nmap -sP $ip
fi

