#!/bin/bash

greenB='\x1b[1;32m'; end='\x1b[0m'
echo -e "本机IP是：$greenB`routel|sed -n '2p'|awk '{print $3}'`$end"
ip=`routel|sed -n '2p'|awk '{print $1$2}'`
if [ $1 ]; then
	# 端口，MAC地址
	sudo /usr/bin/nmap -sS $ip|sed "s/[1-9][0-9.]\{6,14\}/${greenB}&${end}/g"
else
	# 如果对方关闭了icmp，就探测不到
	/usr/bin/nmap -sP $ip|sed "s/[1-9][0-9.]\{6,14\}/${greenB}&${end}/g"
fi

