#!/usr/bin/perl

use 5.010;

$_=defined $ARGV[0]?$ARGV[0]:`xclip -o`;
say;
chomp;
s.^['"]..g; s.['"]$..g;		# 去掉引号包裹，只能处理一个参数。
s.^~.$ENV{HOME}.g;
if(! -e $_){
$_=`locate -n 1 "$_"`;
chomp;
print "locate:\t";
}
s. .\\ .g;
say;
system("xdg-open $_ &");
#if(! $ARGV[0]){
#    `xdg-open $_ &`;
#}else{
#    use File::Basename;
#    $_=dirname($_);
#    say "目录：->$_<-";
#    say "cd \"$_\"\n";	# 只能在bash中使用eval o.pl改变父进程目录。
#}

