#!/usr/bin/perl

use 5.010;

# 从参数或者鼠标选择(primary剪贴板)，快速打开文件。
$_=defined $ARGV[0]?$ARGV[0]:`xclip -o`;
print "input:\t"; say;
chomp;
s.^['"]..g; s.['"]$..g;		# 去掉引号包裹，只能处理一个参数。
s.^~.$ENV{HOME}.g;	# xdg-open 不认 ~ 符号。
if(! -e $_){	# 残缺的文件名或路径，自动补全定位文件。
	if(m"/"){	# 有路径。
		$_=`locate -n 1 -w "$_"`;
	}else{		# 没路径的残缺文件名。
#        $_=`locate -r "$ENV{HOME}/[^.]*$_.*"`;
#        $_=`locate "$ENV{HOME}/*$_*"`;	# 限定在家目录找。
		$_=`locate -b "$_"`;			# 首先出现的是家目录的文件。
		s"^.*/\..*$""mg; s"\n{2,}""g;	# 去掉隐藏目录的行。
		($_)=split "\n";	# 取第一行
	}
}
chomp; print "locate:\t"; s. .\\ .g; say;	# xdg-open 须空格转义。
system("xdg-open $_ &");
