#!/bin/bash

# 使用v2ray来统管shadowsocks+v2ray的json

configpath="$HOME/bin/config/proxy.config"
configfile="*.pac *.json"
logfile="$configpath/vv.log"
v2raycmd="/home/eexpss/bin/app/v2ray-linux-64/v2ray"
revgreenB='\x1b[7;32m'; end='\x1b[0m';

wlog(){
	grep "$1=" $logfile 1>/dev/null
	if [ $? -eq 0 ]; then
		sed -i "s/$1=.*/$1=$key/" $logfile
	else
		echo "$1=$key" >> $logfile
	fi
}

showbold(){
	if [[ $1 == $2 ]]; then
		echo -e "${revgreenB}$3${end}";
	else
		echo "$3";
	fi
}

lastjson=`grep "lastjson=" $logfile | sed 's/.*=//'`
lastproxy=`grep "lastproxy=" $logfile | sed 's/.*=//'`

cd $configpath
showbold $lastproxy "off" "0 --> 关闭全局代理／停止后台"
files[0]="off";

showbold $lastproxy "all" "1 --> 全部数据走代理"
files[1]="all";

index=2; for file in $configfile; do
	files[$index]=$file;
	echo $file|grep "\.pac$" 1>/dev/null && last=$lastproxy || last=$lastjson
	showbold $last $file "$index --> ${files[$index]%.json}";
	((index++));
done
key=99; until [[ $key -lt $index && $key -ge 0 ]]; do read -p  "Please choose config [0-$((index-1))]: " -t 8 -n 1 key; done
# dealy 5 seconds, default choose 0
key=${files[$key]}; echo ""; echo "Choose : $key"

case $key in
	off)
		echo "关闭全局代理／停止后台"
		gsettings set org.gnome.system.proxy mode 'none'
		sudo pkill -9 -x ${v2raycmd##*/}
		wlog lastproxy
		;;
	all)
		echo "全部数据走代理"
		gsettings set org.gnome.system.proxy mode 'manual'
		gsettings set org.gnome.system.proxy.http host ''
		gsettings set org.gnome.system.proxy.https host ''
		gsettings set org.gnome.system.proxy.ftp host ''
		gsettings set org.gnome.system.proxy.socks port 1080
		gsettings set org.gnome.system.proxy.socks host '127.0.0.1'
		wlog lastproxy
		;;
	*.pac)
		echo "自定义代理 $key"
		fullpath="file://$configpath/$key"
		gsettings set org.gnome.system.proxy autoconfig-url "$fullpath"
		gsettings set org.gnome.system.proxy mode 'auto'
		wlog lastproxy
		;;
	*.json)
		echo "切换到v2ray代理 $key"
		sudo pkill -9 -x ${v2raycmd##*/}
		if [ -x $v2raycmd ]; then
			sudo $v2raycmd -config $key &
		else
			echo "没安装命令行的v2ray软件。"; exit
		fi
		wlog lastjson
		;;
esac
