#!/bin/bash

#~ 兼容root，需要软链接到 /root/.bashrc 下面。
if [ -f /etc/bashrc ]; then
	. /etc/bashrc	# CommandNotFound 时，自动安装的功能，在这文件里。
fi

#~ stty -ixon
set -o vi
export VGL_LOGO=1	# Bumbleebee显示右下角VGL标记
export GSK_RENDERER=cairo	# Wayland下, nvidia驱动下，gnome-extensions需要

#-------ALIAS------------------------------------
[ "$(whoami)" == "root" ] && sudostr="" || sudostr="sudo"
##			-------- 软件包管理 --------
if [ -x /usr/bin/apt ]; then
	alias pi="$sudostr apt install"
	alias pr="$sudostr apt remove"
	alias pu="$sudostr apt update && $sudostr apt upgrade"	# /usr/bin/update-manager
	alias pf='apt list'			# 搜索包名
	alias pfi='apt list --installed'	# 搜索已安装的包。
	alias pf0='apt search'			# 搜索描述，参数是AND关系。
	alias pinfo='apt show'
	pfile(){ dpkg -S $@ || apt-file search $@; }	# 查找文件所或命令属的包(已安装/未安装)
	plist(){ dpkg -L $@ || apt-file list $@; }	# 列出包的文件(已安装/未安装)
	#as(){ aptitude search "!~nlib!~ri386!~v $*";}
	alias pwhoneed='apt-cache rdepends'	# 查看谁依赖这个包
	alias pneed='apt-cache depends'		# 查看依赖的包
else
	alias pi="$sudostr dnf install"
	alias pr="$sudostr dnf remove"
	alias pu="$sudostr dnf update"
	alias pf="dnf search -C"
	alias pfi="dnf list --installed -C"
	##			-------- 未安装的包 --------
	# -C 完全从系统缓存运行。长期bug: 1247644。每次都提示导入 GPG 公钥。
	#~ pf(){ dnf search -Cy $@|gc $@; }	# 无安装状态。搜索参数是AND关系。
	#~ pfi(){ dnf list installed "*$1*$2*$3*"|gc $@; }	# 搜索已安装的包。
	# alias pinfo='dnf info -Cy'			# 可通配符查未安装的包说明
	##			-------- 已安装的包 --------
	# 包信息。rpm需要已安装的确切包名；dnf可通配符查未安装的包。
	pinfo(){ rpm -q --info $1 || dnf info -Cy $1; }
	alias pfile='dnf provides -C'				# 查找文件或命令所属的包(已安装/未安装)
	alias pneed='rpm -q --whatrequires'		# 被哪个包需要
	# 包的文件列表。
	plist(){ rpm -q --list $1 || dnf repoquery -Cy --list $1; }

	alias fk="$sudostr flatpak"
	alias fki="$sudostr flatpak install"
	alias fkr="$sudostr flatpak uninstall"
	alias fku="$sudostr flatpak update"
	alias fkf="flatpak search"
	alias fkl="flatpak list --app"
#~ 🔴 flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub  //替换为上海交大源
fi
##------- ---------
#~ https://clang.llvm.org/docs/ClangFormatStyleOptions.html
alias format='clang-format -style=file -i'
alias glog='journalctl -f -o cat /usr/bin/gnome-shell'
alias jlog='journalctl -f -o cat /usr/bin/gjs'
alias wl='env MUTTER_DEBUG_DUMMY_MODE_SPECS=1600x1000 dbus-run-session -- gnome-shell --nested --wayland'
#~ alias wl='env MUTTER_DEBUG_DUMMY_MODE_SPECS=2560×1440 dbus-run-session -- gnome-shell --nested --wayland'
export LC_ALL=zh_CN.UTF-8
alias cn='export LC_ALL=zh_CN.UTF-8'
alias en='export LC_ALL=C'
alias fc-zh='fc-list :lang=zh-cn family file|sed "s,/.*/,,"|sed "s/:\ \(.*\)/\x1b[0;32m\t\1\x1b[0m/"'
alias dms='/usr/bin/dms -path "`pwd`"'	# : Path must be absolute:

alias tail='/usr/bin/tail -n $(($LINES-4))'
alias head='/usr/bin/head -n $(($LINES-4))'
alias pl='perl -pE'	#-E like -e, BUT enables all features; -p EXCUTE while (<>) THEN print.
alias pln='perl -nE'

ocr(){ tesseract "$1" /tmp/ocr -l chi_sim 2>/dev/null && cat /tmp/ocr.txt; }

# alias i='df -hT -x tmpfs -x devtmpfs;echo -e "\n内存---------------";free -h|cut -b -50;echo -e "\n温度---------------";sensors|grep Core'
alias i='df -hT|grep -P "(可用|\/(|home|boot)$)";
echo -e "\n内存---------------";free -h|cut -b -50;
echo -e "\n温度---------------";sensors|grep Core'
	
[ -x /usr/bin/gvim ] && alias v='gvim --remote-tab-silent' && alias sv='sudo gvim'
#alias k='pkill -u `id -un` -9 -f'

#edit=("/usr/bin/gedit" "/usr/bin/io.elementary.code" "/usr/bin/geany" "/usr/bin/gnome-text-editor")
#for ed in "${edit[@]}"; do
#	if [ -x $ed ]; then alias e=$ed; break; fi
#done
alias e='/usr/bin/gnome-text-editor'

alias dog='grep -v -E "(^$|^#|^!)"'
alias ps='\ps -u `id -un` -o pid,command'
alias pg='pgrep -af'
alias k='pkill -9 -f'
alias g='grep --color=always -Pi 2>/dev/null'
alias say='~/.local/bin/edge-playback -v zh-CN-XiaoyiNeural -t'

## -------- xclip写入文件 --------
yy() {	#XA_CLIPBOARD
    if [[ -z "$1" ]]; then
        echo "剪贴板写入文件，需要指定新文件名。"
    else
        xclip -selection clipboard -o > "$1"
    fi
}

y() {		#XA_PRIMARY
	f=${*:-x.摘录.x}
	echo $f
	echo -ne "#\t--------▶  " >>"$f"
	date '+%F %T' | tr -d '\n' >>"$f"
	echo -e " ◀ --------" >>"$f"
	xclip -o  | sed '/'$HOSTNAME'/c--------' >>"$f"
	echo -e "\n" >>"$f"
}

## -------- LS --------
alias l='\ls --color=always'
alias la='l -A'
alias lt='l -oAh  --time-style=iso -t'		# mtime
alias ls='lt -S'		# size

# ------- FUNC ---------
c(){ echo $1|bc -l; }
p(){ ping -c 5 ${1:-www.163.com}; }
u(){ \du -sch "$@" 2>/dev/null|sort -rh; }
# 鼠标选择路径或文件，快速进入目录。
d(){ c=`xclip -o|sed -e "s.^~.$HOME."`; if [ -f "$c" ]; then d=`dirname "$c"`; else d=$c; fi; echo $d; cd "$d";}

export TERM=xterm-256color	# 放在所有tput之前。
#-------LESS TERMCAP for color manpage------------
#0=black 1=red 2=green 3=yellow 4=blue 5=magenta 6=cyan 7=white
#man terminfo: set_a_foreground -> setaf; set_a_background -> setab;
export LESS_TERMCAP_mb=$(tput bold; tput setaf 1)	# enter_bold_mode
export LESS_TERMCAP_md=$(tput bold; tput setaf 1)	# begin bold
export LESS_TERMCAP_me=$(tput sgr0)					# exit_attribute_mode
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4)
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)		# exit_standout_mode
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 2)	# enter_underline_mode
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)		# exit_underline_mode
export LESS_TERMCAP_mr=$(tput rev)		# enter_reverse_mode
export LESS_TERMCAP_mh=$(tput dim)		# enter_dim_mode (half-bright)
#export MANPAGER="/usr/bin/less"
export GROFF_NO_SGR=1	#fix manpage no color in Fedora 25/36

#-------ENVIROMENT SET-----------------------------
if [ "$(whoami)" != "root" ]; then
	export PATH=$HOME/bin:$HOME/.local/bin:$PATH
	export CDPATH=:~:~/bin:~/project:~/.local/share/gnome-shell/extensions/:
fi
#-------PS1 COLOR----------------------------------
	PS1='$(~/bin/prompt.pl "\w")'

#-------HISTORY------------------------------------
shopt -s histappend
PROMPT_COMMAND='history -a'

bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

#bash_completion
. /etc/profile.d/bash_completion.sh
#unset command_not_found_handle
#~ cd	# gnome-termianl 调用此配置前，扩展 note 就乱进了某目录。

#~ eval "$(starship init bash)"
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
alias ss5='proxychains4 -f /home/eexpss/.proxychains/ss5-temp.conf'
alias ss5-update='/home/eexpss/bin/update-socks5-proxies.sh'
