#!/bin/bash

alias d='df -hT -x tmpfs -x devtmpfs'
alias dog='grep -v -E "(^$|^#|^!)"'
alias g='grep -in 2>/dev/null'

alias l='ls -F'
alias lsc='ls -lAhtc'
alias lsm='ls -lAht'
alias lss='ls -lAhS'

alias ps='/bin/ps -w'
alias pg='/usr/bin/pgrep -ln'
p(){ ping -c 5 ${1:-www.163.com}; }

#-------ENVIROMENT SET-----------------------------
pc0='\[\e[1;32;40m\]'
pc1='\[\e[1;37;42m\]'
PS1="$pc0 \H \t $pc1 \w \[\e[m\] ▶ "

