# luna_pinyin.custom.yaml
#
# 【朙月拼音】模糊音定製模板
#   佛振配製 :-)
#
# 位置：
# ~/.config/ibus/rime  (Linux)
# ~/Library/Rime  (Mac OS)
# %APPDATA%\Rime  (Windows)
#
# 於重新部署後生效
# Ctrl+` 組合鍵、菜單。

patch:
  "menu/page_size": 8

    # 模糊音定義
  'speller/algebra':
    - erase/^xx$/                      # 第一行保留

    # 模糊音定義先於簡拼定義，方可令簡拼支持以上模糊音
    - abbrev/^([a-z]).+$/$1/           # 簡拼（首字母）
    - abbrev/^([zcs]h).+$/$1/          # 簡拼（zh, ch, sh）

    - derive/^([zcs])h/$1/             # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/     # z, c, s => zh, ch, sh

    - derive/^n/l/                     # n => l
    - derive/^l/n/                     # l => n
    - derive/^f/h/                     # f => h
    - derive/^h/f/                     # h => f
    - derive/([aeiou])n$/$1ng/            # en => eng, in => ing
    - derive/([aeiou])ng$/$1n/            # eng => en, ing => in
