#!/bin/bash

#bind -x '"\C-l":ls -l'
#-------LESS TERMCAP-------------------------------
export LESS_TERMCAP_mb=$'\033[01;31m' 
export LESS_TERMCAP_md=$'\033[01;31m' 
export LESS_TERMCAP_me=$'\033[0m' 
export LESS_TERMCAP_se=$'\033[0m' 
export LESS_TERMCAP_so=$'\033[01;44m' 
export LESS_TERMCAP_ue=$'\033[0m' 
export LESS_TERMCAP_us=$'\033[01;32m'

#-------ENVIROMENT SET-----------------------------
export PATH=$HOME/bin:$PATH
export CDPATH=:~:~/bin
export RES=$HOME/bin/resources

#PS1='\[\e[31;40m\]\D{%Y-%m-%d %H:%M:%S %a}\[\e[32;40m\] \w \[\e[m\]\n● '
PS1='\[\e[32;40m\]\D{%Y-%m-%d %a} \t \H \w \[\e[m\] \n● '

#-------HISTORY------------------------------------
shopt -s histappend
PROMPT_COMMAND='history -a'

PS4='+{$LINENO:${FUNCNAME[0]}} '
HISTFILESIZE=2000
HISTSIZE=2000
HISTTIMEFORMAT='%F %T '
HISTCONTROL=erasedups
HISTIGNORE="pwd:ls:cd:"

bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

