#!/bin/bash

echo "NAUTILUS_SCRIPT_SELECTED_FILE_PATHS -> $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" > ~/nautilus_script.log
echo "NAUTILUS_SCRIPT_SELECTED_URIS -> $NAUTILUS_SCRIPT_SELECTED_URIS" >> ~/nautilus_script.log
echo "NAUTILUS_SCRIPT_CURRENT_URI -> $NAUTILUS_SCRIPT_CURRENT_URI" >> ~/nautilus_script.log
echo "NAUTILUS_SCRIPT_WINDOW_GEOMETRY -> $NAUTILUS_SCRIPT_WINDOW_GEOMETRY" >> ~/nautilus_script.log
