#!/bin/bash

zenity --width=900 --height=400 --list --column="para" --column="value" --title="nautilus内置参数" \
NAUTILUS_SCRIPT_SELECTED_FILE_PATHS "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" \
NAUTILUS_SCRIPT_SELECTED_URIS "$NAUTILUS_SCRIPT_SELECTED_URIS" \
NAUTILUS_SCRIPT_CURRENT_URI "$NAUTILUS_SCRIPT_CURRENT_URI" \
NAUTILUS_SCRIPT_WINDOW_GEOMETRY "$NAUTILUS_SCRIPT_WINDOW_GEOMETRY"

#~ echo "NAUTILUS_SCRIPT_SELECTED_FILE_PATHS -> $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" > ~/nautilus_script.log
#~ echo "NAUTILUS_SCRIPT_SELECTED_URIS -> $NAUTILUS_SCRIPT_SELECTED_URIS" >> ~/nautilus_script.log
#~ echo "NAUTILUS_SCRIPT_CURRENT_URI -> $NAUTILUS_SCRIPT_CURRENT_URI" >> ~/nautilus_script.log
#~ echo "NAUTILUS_SCRIPT_WINDOW_GEOMETRY -> $NAUTILUS_SCRIPT_WINDOW_GEOMETRY" >> ~/nautilus_script.log
