#!/bin/bash

alias gcc='/usr/bin/gcc `pkg-config --cflags --libs gtk+-2.0 gmodule-2.0`'
alias valac='/usr/bin/valac --pkg gtk+-3.0 --pkg gmodule-2.0'
alias calendar='calendar -A 7'
alias fc-zh='fc-list :lang=zh-cn|sed 's/:.*//''
alias arp.显示='cat /proc/net/arp'

alias ai='sudo apt-get install'
alias ap='sudo apt-get purge'
alias ar='sudo apt-get remove'
alias au='sudo apt-get update && msg 列表已经刷新 || msg 刷新失败'
alias ag='sudo apt-get upgrade'

alias as='aptitude search'
alias aw='aptitude show'

alias lnsf='sudo ln -sf'
alias o='xdg-open'
alias cal='cal -3'
alias ce='crontab -e'
alias cl='crontab -l'
alias cman='man -M /usr/share/man/zh_CN'
alias cn='export LC_ALL=zh_CN.UTF-8'
alias d='df -hT -x tmpfs -x devtmpfs'
alias tail='/usr/bin/tail -n $(($LINES-4))'
alias head='/usr/bin/head -n $(($LINES-4))'
alias dmesg='/bin/dmesg|tail|cut -b -$COLUMNS'
alias dog='grep -v -E "(^$|^#|^!)"'
alias du='du -sch'
alias egrep='egrep --color=auto'
alias en='export LC_ALL=C'
alias free='free -m'
alias g='grep --color -in'
alias disk='palimpsest'

alias proxy.gap='dtach -n /tmp/dtach-gappproxy python ~/bin/gappproxy/localproxy/proxy.py'
alias proxy.cdn='dtach -n /tmp/dtach-cdnproxy ~/bin/cdnproxy'
alias dtach.slimrat='dtach -n /tmp/dtach-slimrat ~/bin/slimrat -l ~/.slimrat/queue'

# w3m -dump 可代替 curl
alias myip='curl http://members.3322.org/dyndns/getip'
alias myip1='curl ifconfig.me/ip'
alias grep='grep --color=auto'
# alias v='/usr/bin/gvim -f --remote-silent-tab'
function v () { (/usr/bin/gvim -f "$@" &) }
alias sv='sudo /usr/bin/gvim --remote-silent-tab'
alias hexdump='hexdump -C'
alias iftop.启动='sudo iftop -i `netname`'
alias irc='irssi -c irc.freenode.net'
alias k9='pkill -9'
alias sk9='sudo pkill -9'
alias l='ls -CF --color'
alias l.='ls -d --color .*'
alias la='ls -AF --color'
alias ld='ls -ld */'
alias ll='ls -lFht --color'
alias lla='ls -AlFht --color'
alias ls='ls --color=auto'
alias m-2-图片合并2列='montage -tile 2 -geometry +0+0 -background none'
alias m-h-横排图片合并='montage -geometry +0+0 -background none'
alias m-v-竖排图片合并='montage -tile 1 -geometry +0+0 -background none'
m-array-pic(){
montage $* null: -thumbnail 260x220 -bordercolor Lavender -background black +polaroid -background LightGray -geometry -26-20 -tile x4 ~/montage-array.jpg
}

# alias mencoder='/usr/bin/mencoder -profile mpeg4'
alias mencoder-c430='/usr/bin/mencoder -profile c430'

alias ml.kill='echo kill | nc -q 1 localhost 4000|sed 1,6d|sed /command-line/,+2d'
alias ml.info='echo vd | nc -q 1 localhost 4000'
alias ml.speed-toggle='echo bw_toggle | nc -q 1 localhost 4000|sed 1,6d|sed /command-line/,+2d'
alias net='echo eexp|sudo -S netstat -tulpn'
alias ntop.启动='sudo ntop -i wlan0'
alias osd='gnome-osd-client'
#alias pg='pgrep -l'
alias ps='/bin/ps -e -o pid,command'
alias rm_empty_dir='find -type d -empty -exec rmdir {} \;'
alias s-ffmpeg-屏幕视频='ffmpeg -f x11grab -s 1280x800 -r 25 -i :0.0 -sameq ~/screen.mpg'
alias s-m视频监测='mencoder tv:// -tv driver=v4l -oac mp3lame -ovc lavc -o ~/监测.mpeg'
alias ss5='gnome-screenshot --delay 5'
alias t.d='tar --delete -f '
alias t.l='tar tf '
alias t.u='tar uPvf '
alias t.x='tar xmPvf '
alias find-opera-1M='find ~/.opera/cache*/ -iname "opr*.tmp" -cmin -60 -size +1000k -printf "------\t%p\t► %Cr\t► %kK\t►" -exec file -b {} \;'
alias tar-opera='t.u ~/opera-setting-`hostname`-`date '+%Y-%m-%d-%H-%M-%S'`.tar `find ~/.opera -iname "*.adr" -or -iname "*.ini" -or -iname "wand.dat" -or -iname "eexp*"`'
osd0(){
gnome-osd-client -f "<message id='oss' osd_vposition='center' osd_halignment='center'><span font='ZhunYuan 180'  foreground='red'>`xsel -o`</span></message>"
}
netname(){
#routel|sed -n "2p"|awk '{print $4}'
routel|grep 'default.*static'|awk '{print $NF}'
}
alias mp3info='mutagen-inspect'
alias mp3enca='mid3iconv --remove-v1 -d -e GBK'
alias loc='locate -beLin $(($LINES-4))'
alias pl='perl -e'
loc.(){
locate -eLin $(($LINES-4)) -r "`pwd`/.*$1"
}
pg(){ /bin/ps -e -o pid,command|grep $1|grep -v grep; }
fd(){ [ $1 ] && find . -iname "*$1*" || echo "need parameter."; }
tree(){ /usr/bin/tree $*|/usr/bin/ascii2uni -a K;}
gitup(){ git ci -a -m "${1:-`date`}"; git remote|grep .; [ $? == 0 ] && git push; }
c(){ echo $1|bc -l; }
cdd(){ d=`dirname "$1"`; echo $d; cd "$d";}
md () { mkdir -p "$1" && cd "$1"; }
nmap(){
/usr/bin/nmap ${1:-localhost}
}
p(){
ping -c 5 ${1:-www.163.com}
}
xargs(){
/usr/bin/xargs -I{} $* {}
}
#--------TAB COMPLETION ADD------------------------
_show_installed()
{
        local cur
        COMPREPLY=()
        cur=`_get_cword`
        COMPREPLY=( $( _comp_dpkg_installed_packages $cur ) )
        return 0
}
_show_all()
{
        local cur
        COMPREPLY=()
        cur=`_get_cword`
        COMPREPLY=( $( apt-cache pkgnames $cur 2> /dev/null ) )
        return 0
}
complete -F _show_all $default aw ai as
complete -F _show_installed $default ap ar
#complete -F _show_installed $default ar
